spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/altonedb
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          generate_statistics: true
    h2:
      console:
        enabled: true

server:
  port: 8090

logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace